---
RecipeFormatVersion: "2020-01-25"
ComponentName: "MqttBridge"
ComponentVersion: "1.0.0"
ComponentDescription: "MQTT Bridging component"
ComponentPublisher: "AWS"
ComponentConfiguration:
  DefaultConfiguration:
    mappings:
      localTopics:
        - "/localTopic"
      cloudTopics:
        - "/cloudTopic"
    connectionInfo:
      brokerUri: "tcp://localhost:1883"
      clientId: "id"
      username: null
      password: null
    accessControl:
      aws.greengrass.ipc.mqttproxy:
        bridgePolicy1:
          policyDescription: "Allows access to publish and subscribe to all topics."
          operations:
            - "aws.greengrass#PublishToIoTCore"
            - "aws.greengrass#SubscribeToIoTCore"
          resources:
            - "*"
Manifests:
  - Platform:
      os: "*"
    Name: "All"
    Lifecycle:
      Startup: "java -jar {artifacts:path}/aws.greengrass.MqttBridgeExample.jar"
    Artifacts:
      - Uri: "s3://<BUCKET_NAME>/aws.greengrass.MqttBridgeExample.jar"
