---
RecipeFormatVersion: "2020-01-25"
ComponentName: "com.example.ConfigUpdater"
ComponentVersion: "1.0.0"
ComponentType: "aws.greengrass.generic"
ComponentDescription:
  "Component that updates its own configuration every 2 seconds"
ComponentPublisher: "Amazon"
ComponentConfiguration:
  DefaultConfiguration:
    counter: 0
Manifests:
  - Platform:
      os: "linux"
      runtime: "*"
    Lifecycle:
      install:
        RequiresPrivilege: false
        Script: "python3 -m venv ./venv && . ./venv/bin/activate && python3 -m
          pip install\
          \ awsiotsdk"
      run:
        RequiresPrivilege: false
        Script:
          ". ./venv/bin/activate && python3  {artifacts:path}/config_updater.py"
    Artifacts:
      - Uri: "s3://sample/config_updater.py"
        Permission:
          Read: "OWNER"
          Execute: "OWNER"
Lifecycle: {}
