name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  run-checks:
    timeout-minutes: 60
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: formatting
            check: formatting
          - name: spelling
            check: spelling
    name: Check ${{ matrix.name }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
          filter: "tree:0"
      - name: Install Nix
        run:
          curl --proto '=https' --tlsv1.2 -sSf -L
          https://install.lix.systems/lix | sh -s -- install --no-confirm

      - name: Check ${{ matrix.name }}
        run: |
          sudo tee -a /etc/nix/nix.conf > /dev/null <<EOF
          log-lines = 0
          EOF
          nix build -L .#checks.x86_64-linux.${{ matrix.check }}
